AWSTemplateFormatVersion: "2010-09-09"
Description: Set up DNS records for the ELB.

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: The environment for which the Route 53 records needs to be created.

  DNSName:
    Type: String
    Description: The URL of the load balancer to deploy.

  DomainName:
    Type: String
    Default: apps.flaretx.com.
    Description: The URL of the domain to apply the change to.

  HostedZoneId:
    Type: String
    Default: Z02553703C325QRBKLZMV
    Description: The ID of the hosted zone


Conditions:
  isProd: !Equals [!Ref Environment, "production"]
    
Resources: 
  IngressControllerMapping:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref DomainName
      Comment: !Sub "Routing for Biomage SCP ${Environment} cluster"
      RecordSets:
      - Name: !Join ['.', [!If [isProd, "scp", !Sub "scp-${Environment}"], !Ref DomainName]]
        Type: A
        AliasTarget:
          DNSName: !Ref DNSName
          HostedZoneId: !Ref HostedZoneId
      - Name: !Join ['.', ['*', !If [isProd, "scp", !Sub "scp-${Environment}"], !Ref DomainName]]
        Type: A
        AliasTarget:
          DNSName: !Ref DNSName
          HostedZoneId: !Ref HostedZoneId
