apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: 503-for-pending-subscriptions
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:us-east-2:776724186643:certificate/dbf65af1-ca1d-4055-bbd7-04a8c3894347
    alb.ingress.kubernetes.io/group.name: "{{ .Values.clusterEnv }}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.order: '1000'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.response-503: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"The subscription endpoint is not available yet."}}
spec:
  rules:
    - http:
        paths:
          - path: /v1/pipelineResults
            backend:
              serviceName: response-503
              servicePort: use-annotation
          - path: /v1/gem2sResults
            backend:
              serviceName: response-503
              servicePort: use-annotation
